# Generated by Django 6.0.6 on 2026-06-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('enseignant_prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=150, null=True)),
                ('module', models.CharField(blank=True, max_length=150, null=True)),
                ('semestre', models.CharField(blank=True, max_length=10, null=True)),
                ('heures_enseignement', models.FloatField(default=0)),
                ('heures_greta', models.FloatField(default=0)),
                ('heures_service', models.FloatField(default=0)),
                ('ordre', models.IntegerField(default=0)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='compositions.composition')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
