# Generated by Django 6.0.6 on 2026-07-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_action', models.CharField(max_length=150)),
                ('lieu', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=100)),
                ('public', models.CharField(max_length=200)),
                ('effectif', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant_id', models.IntegerField()),
                ('enseignant_nom', models.CharField(max_length=100)),
                ('enseignant_prenom', models.CharField(max_length=100)),
                ('enseignant_email', models.CharField(blank=True, max_length=150, null=True)),
                ('enseignant_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('statut', models.CharField(blank=True, max_length=100, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=150, null=True)),
                ('ministere_collectivite', models.CharField(blank=True, max_length=150, null=True)),
                ('code_matiere', models.CharField(max_length=40)),
                ('intitule_matiere', models.CharField(blank=True, max_length=150, null=True)),
                ('volume_horaire', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('semestre', models.CharField(blank=True, max_length=10)),
                ('heures_enseignement', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('heures_greta', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('heures_service', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='compositions.composition')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
