# Generated by Django 6.0.6 on 2026-06-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompositionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_matiere', models.IntegerField()),
                ('id_enseignant', models.IntegerField()),
                ('coefficient', models.FloatField()),
                ('volume_horaire', models.FloatField()),
                ('ordre', models.IntegerField(default=0)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='compositions.composition')),
            ],
        ),
    ]
