# Generated by Django 6.0.6 on 2026-06-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enseignant', models.IntegerField()),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('heures_totales', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RapportEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.IntegerField()),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('heures_totales', models.FloatField(default=0)),
            ],
        ),
    ]
